controllers:
    resource: ../src/Controller/
    type: annotation

register:
    path: /register
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    methods: App\Controller\LoginController::login

app_logout:
    path: /logout
    methods: App\Controller\LogoutController::logout

kernel:
    resource: ../src/Kernel.php
    type: annotation
