controllers:
    resource: ../src/Controller/
    type: annotation

register:
    path: /register
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    methods: App\Controller\LoginController::login

app_logout:
    path: /logout
    methods: GET

kernel:
    resource: ../src/Kernel.php
    type: annotation



formation_add:
    path: /add
    controller: App\Controller\CreateFormController::index

formation_show:
    path: /show/{url}
    controller: App\Controller\CreateFormController::show

formation_edit:
    path: /edit/{id}
    controller: App\Controller\CreateFormController::edit
    requirements:
        id: '\d+'

formation_remove:
    path: /remove/{id}
    controller: App\Controller\CreateFormController::remove
    requirements:
        id: '\d+'
